### ISSUE TITLE
Document running Fleet persistently with a systemd unit file

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1593]

**Comment by groob** [comment]
I recently documented how to do this in another project. 

https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-systemd

The directions should be _very_ similar since both are static binaries, just replace the binary name.

If someone could PR a changed version of that document to the Fleet docs folder, it would be much appreciated.

**Comment by jplock** [comment]
I ended up doing:

```
[Unit]
Description=Kolide Fleet
After=network.target

[Service]
ExecStart=/usr/local/bin/fleet serve -c /etc/fleet/fleet.yml

[Install]
WantedBy=multi-user.target
```
