### ISSUE TITLE
Add Support for file_accesses in the FIM Configuration

### ISSUE THREAD

**Issue by bcoverston** [kolide/fleet#1708]
Poking around in the latest Fleet, I was trying to enable FIM. I thought I enabled it, but I wasn't seeing file accesses. I requested the document I posted, and it's apparent that the current implementation silently ignores all `file_accesses` in the patch request.

For reference, the original patch request that added this functionality is here:
https://github.com/kolide/fleet/pull/1548/files

It appears that fixing this would mostly be a matter of adding properties to a few of the structures so that it accepts and serializes the necessary bits to the configuration. Happy to volunteer for the work, but I'm curious if you're aware of any sharp edges on this before I get started.

**Comment by zwass** [comment]
@bcoverston I'm not sure that just changing those structs will be sufficient. I took a look at the example you posted in chat:

```
{
  "interval": 500,
  "file_paths": {
    "homes": [
      "/root/.ssh/%%",
      "/home/%/.ssh/%%"
    ],
    "etc": [
      "/etc/%%"
    ],
    "cassandra": [
      "/media/ebs_lvm/cassandra/%%"
    ]
  },
  "file_accesses": ["cassandra","etc","homes"]
}
```

Because `file_accesses` is not a subkey of `file_paths`, I don't think the existing DB code is going to work with this without modification. That said, feel free to poke around further as I didn't write this code and may be misinterpreting.

I'll note that this will be fully supported by `fleetctl`, which is coming Real Soon™.

**Comment by bcoverston** [comment]
#1717 pull request added for FIM config
