### ISSUE TITLE
No SQL error feedback

### ISSUE THREAD

**Issue by Jackbennett** [kolide/fleet#1712]
### What did you do?
Created a query and added to a pack to run against all hosts, which was;

```sql 
SELECT physical_memory FROM system_info
```

### What did you expect to see?
Query results returned.

### What did you see instead?
x of x hosts successfully ran query. Nothing at all returned.

Note that the sql statement is missing the semicolon to end it. So osquery will happily take that then do nothing as it's waiting for more of the statement.

### Improvement
This it a little thing but there's such nice UI in the sql editor it would be good UX to catch this as it's so easily done. I don't know if it's a good idea to automatically add it at the end but there could at least be some sort of highlight warning.

**Comment by zwass** [comment]
The semicolon is unnecessary in any context outside of `osqueryi`, so that's not the issue you are running into. I'm interested in digging deeper to try to understand what is the issue.

You mention both "added to a pack to run against all hosts" which suggests you scheduled the query, and "x of x hosts successfully ran query. Nothing at all returned." which suggests you ran a distributed query. Which did you do? Are you still encountering this problem?
