### ISSUE TITLE
Feature request: osqueryd configuration options by label/OS group

### ISSUE THREAD

**Issue by mari0d** [kolide/fleet#1738]
At kolide/config/options (Manage Additional Osquery Options) provide a mechanism to apply options by label (eg. apply disable_events flags to only Windows hosts).

**Comment by zwass** [comment]
We intend to allow options to be set by platform in a future release (see https://github.com/kolide/fleet/issues/1586).

As for setting options by labels, we have intentionally not added that as it is not clear how conflicting options (because a host could be in multiple labels with different options) should be merged to generate the final set of options for a host.

If you want to set specific options on a host right now, you can set those options in the flagfile that you pass to osqueryd. Then just don't set the option in the Fleet UI.

**Comment by marpaia** [comment]
#1792 merged fleetctl into master, resolving this issue for 2.0.0
