### ISSUE TITLE
Delay in enumerating Targets with a fleet of ~5000 machines

### ISSUE THREAD

**Issue by audibleblink** [kolide/fleet#1758]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 1.0.8
  branch: 	changelog_1.0.8
  revision: 	eb85e71181c90082808107ecabf655bcea94a117
  build date: 	2018-05-04T00:01:31Z
  build user: 	zwass
  go version: 	go1.9.2

### What operating system are you using?
Ubuntu 18.04

### What did you do?
Visited /query/new

### What did you expect to see?
Populated Targets becomes available for interaction

### What did you see instead?
Populated Targets are not accessible for ~15 seconds

![image](https://user-images.githubusercontent.com/4605783/39650672-0e6f285a-4fb7-11e8-94f6-e2dcbd503ca6.png)

**Comment by zwass** [comment]
@audibleblink I finally had some time to dig into this issue and here's what I found:

With 5,000 hosts enrolled, the `targets` endpoint returns under 100ms, even when using MySQL running in Docker on the same laptop as the Fleet server (eg. not an optimized MySQL server). This seems totally reasonable.

_However_

With 5,000 hosts actively checking in on short intervals, the MySQL server CPU is steadily maxed out. When the `targets` endpoint is hit with the MySQL CPU maxed, it takes on the order of 15s to return.

My suspicion is that your MySQL CPU usage is maxed out, and this is really what the underlying issue is. Can you check your MySQL CPU usage? And your `distributed_interval`, `config_refresh`, and `logger_tls_period` flags for the osquery clients?

**Comment by audibleblink** [comment]
hey @zwass.
I no longer have access to this deployment. That all sounds right though
