### ISSUE TITLE
Allow more aggressive cleanup of hosts

### ISSUE THREAD

**Issue by patrickod** [kolide/fleet#1860]
When using fleet in an environment that consists of a large number of ephemeral hosts the number of "offline" hosts can grow considerably, leading to unexpected behavior.

In environments like our own with disposable VMs and where there's a considerable difference between the peak and trough numbers of live hosts the "offline" status for hosts serves no function as once a host goes "offline" (is terminated) it will never reappear online.

Ideally it'd be possible to set more aggressive cleanup intervals for hosts by platform, as were we to start using this same deployment of fleet with our OS X endpoints *which do go offline* we'd obviously prefer not to have these temporarily offline hosts removed from fleet.

**Comment by crimsonknave** [comment]
I would love to see something in the UI that helps to deal with ephemeral hosts. I have a script that will clean up hosts, but I'd love to be able to mark some hosts as permanent and see them as offline, but others as ephemeral and have them not be visible.

Another option would be something that checks if offline hosts still exist, and are just not enrolled, or if they've been destroyed.

**Comment by zwass** [comment]
Circling back to this, what do folks think would be the most useful behavior? Add the option to automatically delete hosts that haven't checked in within X days?

**Comment by benbasscom** [comment]
I do like the idea of having an admin set config that allows for purging after X days since last checked in.  If it happens to be a client that was stuck in a drawer for a while when it is turned back on it should re-enroll.  

For truly ephemeral clients - what would be the best way to mark them as ephemeral?  If we could easily and consistently mark them, then we could do that as well as the purge after X days since last check in.  Maybe a custom label so the admin can determine what is ephemeral in their environment?

**Comment by patrickod** [comment]
@zwass automatic deletion of all hosts after N days of inactivity would be a great start and would make life a lot easier in deployments like ours.

**Comment by crimsonknave** [comment]
Having some automatic cleanup would be nice, but if that's the case, I'd really like the ability to mark hosts as important or something so that they won't get cleaned up. That, or I'd like to be able to have a list of hosts that I expect to always be enrolled. When you're dealing with thousands of hosts, most of which are ephemeral it's hard to pick out those few critical servers that should always be online and enrolled.

**Comment by jusuos** [comment]
I think an optional toggle to where you can set hosts to be cleaned out after n days of no connectivity would be useful (n= 1-180 or something), and the minimum to make this useful. Features that could be added down the line:
- listing some hosts as "important"
- sending email alert of hosts being deleted in the next 24 hrs
- different settings for different groups, based on some kind of tagging

But I would be very happy with just number 1 at this point.

**Comment by clong** [comment]
> automatic deletion of all hosts after N days of inactivity would be a great start and would make life a lot easier in deployments like ours. 

^^ +1. The other features being mentioned are a "nice to have" for us, but this is the most needed.

It would also be awesome to be able to manually unenroll a single host at a time through the UI via a "remove from fleet" or "unenroll" button.
