### ISSUE TITLE
How to install and run Fleet on Windows

### ISSUE THREAD

**Issue by rpr5x** [kolide/fleet#1997]
Hello. I'm looking to set up Fleet on a Windows 10 Pro machine but don't know exactly how to proceed. It seems like the Docker container approach is the easiest route so I pulled the `kolite/fleet` image off Docker Hub. I also cloned this GitHub repository and ran `docker-compose up` to start the MySQL and Redis services in Docker. However, when I tried to start a container based off the `kolide/fleet` image, I received the following error:
```
ts=2019-01-22T19:46:33.846474Z mysql="could not connect to db: dial tcp 127.0.0.1:3306: connect: connection refused, sleeping 0s"
```

I assume this means that the `kolide/fleet` container can't see the `mysql` container because they're on different networks. Am I supposed to add this image as a new service to the `docker-compose.yml` file?

Just to clarify, my current goal is to get Fleet up and running on my Windows 10 pro machine. After that, I want to add the same Windows host (which is running OsQuery) to Fleet. Later on, I plan to add more hosts as well. Thank you for your assistance.

**Comment by groob** [comment]
Fleet has configuration flags which you can use to specify the hostname for your mysql database. Read through `fleet serve —help` carefully to see what you need to configure in order to get fleet up and running. 

If you’re trying to run fleet for a production environment I do not recommend the `docker-compose.yaml` file in the repo. It’s only there as a dependency for development. Use it if you plan to modify fleet and add / test features. For a production environment create a separate compose file, or deploy fleet in another way. We have a section in the `docs` folder of this repo which describes how to configure fleet for production. 

The #kolide channel in osquery slack is best for these kinds of questions.

**Comment by nikhilkhairnar** [comment]
hi can you please provide the steps to add windows as host in kolide
