### ISSUE TITLE
Unable to compile fleet

### ISSUE THREAD

**Issue by medtemo** [kolide/fleet#2102]
I am unable to compile fleet.

fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements
Makefile:173: recipe for target 'deps-go' failed

Ubuntu 16.04.6 LTS
nodejs v12.9.1
go version go1.11.13

**Comment by eliransCyberhat** [comment]
**#metoo2019**
Last week everything passed without any issues.
😔

**Comment by eliranshemtov** [comment]
#metoo2019
Even though last week everything went well, yesterday and today I wasn't able to build the fleet server.
A possible workaround that worked for me:

1. Run `go get github.com/apache/thrift`
2. Edit the file '$GOPATH/src/github.com/kolide/fleet/go.mod' so that the thrift "require" line will look like this: `github.com/apache/thrift v0.12.0`
3. Run `make deps`

**Comment by eliranshemtov** [comment]
#metoo
seems like the entire apache's git is down and teams at apache are investigating at the moment.
![image](https://user-images.githubusercontent.com/16760214/64111578-be66c600-cd8d-11e9-8786-564eb3d5de18.png)

Details and updates could be found here:
[Apache services status online](https://status.apache.org/)

**Comment by joshuaganger** [comment]
the go.mod can be changed to use https://github.com/apache/thrift v0.12.0 instead of git.apache.org and this works for make deps at least.  It fails in "make" though, not sure where else this needs to be updated.

Overall though the process of attempting to compile and build this application has been tedious and fraught with errors.  I've been dealing with dependencies for over an hour.

**Comment by straffin** [comment]
Apache apparently did not consider git.apache.org to be an externally important service, indicating that their mirror to github should be used instead:
![image](https://user-images.githubusercontent.com/4968041/64648001-12098d00-d3e8-11e9-8c84-b7b5860b1a93.png)
All references to git.apache.org in fleet, launcher, and any other code should be changed.
