### ISSUE TITLE
Remove classnames JavaScript library

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#357]
Right now, we use the classnames JavaScript library: https://github.com/JedWatson/classnames. Let's consider removing it in favor of something minimal and built-in.

**Comment by ferhatelmas** [comment]
@marpaia you updated 6 days ago but wanted to check with you before doing anything since what is written in the description is wrong now even if was correct at the issue creation time.

What is the actual plan now ?

* Remove it
* Replace it so with what ?
* Keep it so this issue is not valid anymore

**Comment by marpaia** [comment]
Hey, yeah, sorry, I'm just going to close this. We had an issue with classnames a while ago while we were converting some code to ES6 modules, thus the spirited issue.
